global using Impart.WinUI.Common.Extensions;
global using Microsoft.UI;
global using Microsoft.UI.Input;
global using Microsoft.UI.Windowing;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Media;
global using System;
global using System.Collections.Generic;